title: Yash Bhiwania
author: Yash Bhiwania
email: yashbhiwania772@gmail.com
description: >- 
  Systems programming, embedded development, and my GSoC 2026 journey with the RTEMS Project.
theme: minima
